/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as borrowCreditSol from './BorrowCredit.sol/index.js';
export type { borrowCreditSol };
import type * as oracleSol from './Oracle.sol/index.js';
export type { oracleSol };
import type * as positionSol from './Position.sol/index.js';
export type { positionSol };
import type * as sharesSol from './Shares.sol/index.js';
export type { sharesSol };
import type * as vaultSol from './Vault.sol/index.js';
export type { vaultSol };