/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace Types {
      
    export type JSONStruct = {value: string}

    export type JSONStructOutput = [value: string] & {value: string }
  
    }

  export interface BorrowCreditInterface extends Interface {
    getFunction(nameOrSignature: "addAccessiblePool" | "addToWhitelist" | "createCredits" | "creditInfo" | "decrementCredits" | "incrementCredits" | "oracle" | "owner" | "removeAccessiblePool" | "removeFromWhitelist" | "renounceOwnership" | "replenish" | "setOracle" | "spend" | "transferOwnership" | "whitelisted"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddedAccessiblePool" | "CreateCredits" | "CreditReplenished" | "CreditSpent" | "DecrementedCredits" | "IncrementedCredits" | "OwnershipTransferred" | "RemovedAccessiblePool"): EventFragment;

    encodeFunctionData(functionFragment: 'addAccessiblePool', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'addToWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createCredits', values: [AddressLike, Types.JSONStruct, BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'creditInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'decrementCredits', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'incrementCredits', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeAccessiblePool', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeFromWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'replenish', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'spend', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'whitelisted', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addAccessiblePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addToWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCredits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creditInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decrementCredits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementCredits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAccessiblePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeFromWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'replenish', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelisted', data: BytesLike): Result;
  }

  
    export namespace AddedAccessiblePoolEvent {
      export type InputTuple = [to: AddressLike, pool: AddressLike];
      export type OutputTuple = [to: string, pool: string];
      export interface OutputObject {to: string, pool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreateCreditsEvent {
      export type InputTuple = [to: AddressLike, metadata: Types.JSONStruct, credits: BigNumberish, pools: AddressLike[]];
      export type OutputTuple = [to: string, metadata: Types.JSONStructOutput, credits: bigint, pools: string[]];
      export interface OutputObject {to: string, metadata: Types.JSONStructOutput, credits: bigint, pools: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditReplenishedEvent {
      export type InputTuple = [pool: AddressLike, borrower: AddressLike, credits: BigNumberish];
      export type OutputTuple = [pool: string, borrower: string, credits: bigint];
      export interface OutputObject {pool: string, borrower: string, credits: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditSpentEvent {
      export type InputTuple = [pool: AddressLike, borrower: AddressLike, credits: BigNumberish];
      export type OutputTuple = [pool: string, borrower: string, credits: bigint];
      export interface OutputObject {pool: string, borrower: string, credits: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DecrementedCreditsEvent {
      export type InputTuple = [from: AddressLike, credits: BigNumberish];
      export type OutputTuple = [from: string, credits: bigint];
      export interface OutputObject {from: string, credits: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IncrementedCreditsEvent {
      export type InputTuple = [to: AddressLike, credits: BigNumberish];
      export type OutputTuple = [to: string, credits: bigint];
      export interface OutputObject {to: string, credits: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemovedAccessiblePoolEvent {
      export type InputTuple = [to: AddressLike, pool: AddressLike];
      export type OutputTuple = [to: string, pool: string];
      export interface OutputObject {to: string, pool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BorrowCredit extends BaseContract {
    
    connect(runner?: ContractRunner | null): BorrowCredit;
    waitForDeployment(): Promise<this>;

    interface: BorrowCreditInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAccessiblePool: TypedContractMethod<
      [to: AddressLike, pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addToWhitelist: TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createCredits: TypedContractMethod<
      [_to: AddressLike, _metadata: Types.JSONStruct, _available: BigNumberish, _accessiblePools: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    creditInfo: TypedContractMethod<
      [arg0: AddressLike, ],
      [[Types.JSONStructOutput, bigint, bigint, bigint] & {metadata: Types.JSONStructOutput, available: bigint, used: bigint, updatedAt: bigint }],
      'view'
    >
    

    
    decrementCredits: TypedContractMethod<
      [from: AddressLike, credits: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    incrementCredits: TypedContractMethod<
      [to: AddressLike, credits: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeAccessiblePool: TypedContractMethod<
      [to: AddressLike, pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeFromWhitelist: TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    replenish: TypedContractMethod<
      [borrower: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setOracle: TypedContractMethod<
      [_oracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    spend: TypedContractMethod<
      [borrower: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    whitelisted: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAccessiblePool'): TypedContractMethod<
      [to: AddressLike, pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addToWhitelist'): TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createCredits'): TypedContractMethod<
      [_to: AddressLike, _metadata: Types.JSONStruct, _available: BigNumberish, _accessiblePools: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creditInfo'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[Types.JSONStructOutput, bigint, bigint, bigint] & {metadata: Types.JSONStructOutput, available: bigint, used: bigint, updatedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'decrementCredits'): TypedContractMethod<
      [from: AddressLike, credits: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'incrementCredits'): TypedContractMethod<
      [to: AddressLike, credits: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeAccessiblePool'): TypedContractMethod<
      [to: AddressLike, pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeFromWhitelist'): TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'replenish'): TypedContractMethod<
      [borrower: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOracle'): TypedContractMethod<
      [_oracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'spend'): TypedContractMethod<
      [borrower: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'whitelisted'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'AddedAccessiblePool'): TypedContractEvent<AddedAccessiblePoolEvent.InputTuple, AddedAccessiblePoolEvent.OutputTuple, AddedAccessiblePoolEvent.OutputObject>;
getEvent(key: 'CreateCredits'): TypedContractEvent<CreateCreditsEvent.InputTuple, CreateCreditsEvent.OutputTuple, CreateCreditsEvent.OutputObject>;
getEvent(key: 'CreditReplenished'): TypedContractEvent<CreditReplenishedEvent.InputTuple, CreditReplenishedEvent.OutputTuple, CreditReplenishedEvent.OutputObject>;
getEvent(key: 'CreditSpent'): TypedContractEvent<CreditSpentEvent.InputTuple, CreditSpentEvent.OutputTuple, CreditSpentEvent.OutputObject>;
getEvent(key: 'DecrementedCredits'): TypedContractEvent<DecrementedCreditsEvent.InputTuple, DecrementedCreditsEvent.OutputTuple, DecrementedCreditsEvent.OutputObject>;
getEvent(key: 'IncrementedCredits'): TypedContractEvent<IncrementedCreditsEvent.InputTuple, IncrementedCreditsEvent.OutputTuple, IncrementedCreditsEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RemovedAccessiblePool'): TypedContractEvent<RemovedAccessiblePoolEvent.InputTuple, RemovedAccessiblePoolEvent.OutputTuple, RemovedAccessiblePoolEvent.OutputObject>;

    filters: {
      
      'AddedAccessiblePool(address,address)': TypedContractEvent<AddedAccessiblePoolEvent.InputTuple, AddedAccessiblePoolEvent.OutputTuple, AddedAccessiblePoolEvent.OutputObject>;
      AddedAccessiblePool: TypedContractEvent<AddedAccessiblePoolEvent.InputTuple, AddedAccessiblePoolEvent.OutputTuple, AddedAccessiblePoolEvent.OutputObject>;
    

      'CreateCredits(address,tuple,uint256,address[])': TypedContractEvent<CreateCreditsEvent.InputTuple, CreateCreditsEvent.OutputTuple, CreateCreditsEvent.OutputObject>;
      CreateCredits: TypedContractEvent<CreateCreditsEvent.InputTuple, CreateCreditsEvent.OutputTuple, CreateCreditsEvent.OutputObject>;
    

      'CreditReplenished(address,address,uint256)': TypedContractEvent<CreditReplenishedEvent.InputTuple, CreditReplenishedEvent.OutputTuple, CreditReplenishedEvent.OutputObject>;
      CreditReplenished: TypedContractEvent<CreditReplenishedEvent.InputTuple, CreditReplenishedEvent.OutputTuple, CreditReplenishedEvent.OutputObject>;
    

      'CreditSpent(address,address,uint256)': TypedContractEvent<CreditSpentEvent.InputTuple, CreditSpentEvent.OutputTuple, CreditSpentEvent.OutputObject>;
      CreditSpent: TypedContractEvent<CreditSpentEvent.InputTuple, CreditSpentEvent.OutputTuple, CreditSpentEvent.OutputObject>;
    

      'DecrementedCredits(address,uint256)': TypedContractEvent<DecrementedCreditsEvent.InputTuple, DecrementedCreditsEvent.OutputTuple, DecrementedCreditsEvent.OutputObject>;
      DecrementedCredits: TypedContractEvent<DecrementedCreditsEvent.InputTuple, DecrementedCreditsEvent.OutputTuple, DecrementedCreditsEvent.OutputObject>;
    

      'IncrementedCredits(address,uint256)': TypedContractEvent<IncrementedCreditsEvent.InputTuple, IncrementedCreditsEvent.OutputTuple, IncrementedCreditsEvent.OutputObject>;
      IncrementedCredits: TypedContractEvent<IncrementedCreditsEvent.InputTuple, IncrementedCreditsEvent.OutputTuple, IncrementedCreditsEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RemovedAccessiblePool(address,address)': TypedContractEvent<RemovedAccessiblePoolEvent.InputTuple, RemovedAccessiblePoolEvent.OutputTuple, RemovedAccessiblePoolEvent.OutputObject>;
      RemovedAccessiblePool: TypedContractEvent<RemovedAccessiblePoolEvent.InputTuple, RemovedAccessiblePoolEvent.OutputTuple, RemovedAccessiblePoolEvent.OutputObject>;
    
    };
  }