/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BorrowCredit', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BorrowCredit__factory>
getContractFactory(name: 'Oracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Oracle__factory>
getContractFactory(name: 'Position', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Position__factory>
getContractFactory(name: 'Shares', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Shares__factory>
getContractFactory(name: 'Vault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Vault__factory>
getContractFactory(name: 'NGN', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NGN__factory>
getContractFactory(name: 'USDT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.USDT__factory>
getContractFactory(name: 'IBorrowCredit', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBorrowCredit__factory>
getContractFactory(name: 'IOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOracle__factory>
getContractFactory(name: 'IPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPool__factory>
getContractFactory(name: 'IPosition', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPosition__factory>
getContractFactory(name: 'IShares', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IShares__factory>
getContractFactory(name: 'PoolHelper', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoolHelper__factory>
getContractFactory(name: 'MarketPlace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MarketPlace__factory>
getContractFactory(name: 'Pool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Pool__factory>
getContractFactory(name: 'PoolFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoolFactory__factory>

  getContractAt(name: 'BorrowCredit', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BorrowCredit>
getContractAt(name: 'Oracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Oracle>
getContractAt(name: 'Position', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Position>
getContractAt(name: 'Shares', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Shares>
getContractAt(name: 'Vault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Vault>
getContractAt(name: 'NGN', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NGN>
getContractAt(name: 'USDT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.USDT>
getContractAt(name: 'IBorrowCredit', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBorrowCredit>
getContractAt(name: 'IOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOracle>
getContractAt(name: 'IPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPool>
getContractAt(name: 'IPosition', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPosition>
getContractAt(name: 'IShares', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IShares>
getContractAt(name: 'PoolHelper', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoolHelper>
getContractAt(name: 'MarketPlace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MarketPlace>
getContractAt(name: 'Pool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Pool>
getContractAt(name: 'PoolFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoolFactory>

  deployContract(name: 'BorrowCredit', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BorrowCredit>
deployContract(name: 'Oracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Oracle>
deployContract(name: 'Position', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Position>
deployContract(name: 'Shares', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Shares>
deployContract(name: 'Vault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Vault>
deployContract(name: 'NGN', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NGN>
deployContract(name: 'USDT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.USDT>
deployContract(name: 'IBorrowCredit', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBorrowCredit>
deployContract(name: 'IOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOracle>
deployContract(name: 'IPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPool>
deployContract(name: 'IPosition', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPosition>
deployContract(name: 'IShares', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IShares>
deployContract(name: 'PoolHelper', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolHelper>
deployContract(name: 'MarketPlace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MarketPlace>
deployContract(name: 'Pool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pool>
deployContract(name: 'PoolFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolFactory>

  deployContract(name: 'BorrowCredit', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BorrowCredit>
deployContract(name: 'Oracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Oracle>
deployContract(name: 'Position', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Position>
deployContract(name: 'Shares', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Shares>
deployContract(name: 'Vault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Vault>
deployContract(name: 'NGN', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NGN>
deployContract(name: 'USDT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.USDT>
deployContract(name: 'IBorrowCredit', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBorrowCredit>
deployContract(name: 'IOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOracle>
deployContract(name: 'IPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPool>
deployContract(name: 'IPosition', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPosition>
deployContract(name: 'IShares', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IShares>
deployContract(name: 'PoolHelper', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolHelper>
deployContract(name: 'MarketPlace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MarketPlace>
deployContract(name: 'Pool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pool>
deployContract(name: 'PoolFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolFactory>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  