/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ngnSol from './NGN.sol/index.js';
export type { ngnSol };
import type * as usdtSol from './USDT.sol/index.js';
export type { usdtSol };