/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iBorrowCreditSol from './IBorrowCredit.sol/index.js';
export * as iOracleSol from './IOracle.sol/index.js';
export * as iPoolSol from './IPool.sol/index.js';
export * as iPositionSol from './IPosition.sol/index.js';
export * as iSharesSol from './IShares.sol/index.js';