/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IOracle, IOracleInterface } from "../../../interfaces/IOracle.sol/IOracle.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "credit",
        "type": "uint256"
      }
    ],
    "name": "CreditToAssetSet",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "getCredits",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IOracle__factory {
    static readonly abi = _abi;
    static createInterface(): IOracleInterface {
      return new Interface(_abi) as IOracleInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IOracle {
      return new Contract(address, _abi, runner) as unknown as IOracle;
    }
  }
  