/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBorrowCreditSol from './IBorrowCredit.sol/index.js';
export type { iBorrowCreditSol };
import type * as iOracleSol from './IOracle.sol/index.js';
export type { iOracleSol };
import type * as iPoolSol from './IPool.sol/index.js';
export type { iPoolSol };
import type * as iPositionSol from './IPosition.sol/index.js';
export type { iPositionSol };
import type * as iSharesSol from './IShares.sol/index.js';
export type { iSharesSol };