/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as borrowCreditSol from './BorrowCredit.sol/index.js';
export * as oracleSol from './Oracle.sol/index.js';
export * as positionSol from './Position.sol/index.js';
export * as sharesSol from './Shares.sol/index.js';
export * as vaultSol from './Vault.sol/index.js';